version: '2'
services:
    testcon:
      image: 'fuseteam/lemp-webapp'
      ports:
        - '8090:80'
      volumes:
        - 'documentroot:/var/www'
        - 'data:/var/lib/mysql-data'
    localtunnel:
      image: 'efrecon/localtunnel'
      links:
        - testcon
      command:
        --local-host testcon --port 80 --subdomain nummus
#${PWD} resolves to the current path docker-compose is called from if and only if the user is added to the docker group
#if you need sudo to run docker-compose please replace ${PWD} to the full path to the folders where you like documentroot and data to be mounted
#docker will not create the folders in question the folders must be created before running docker-compose
volumes:
  documentroot:
    driver: local
    driver_opts:
        type: none
        o: bind
        device: "${PWD}/www"
  data:
    driver: local
    driver_opts:
        type: none
        o: bind
        device: "${PWD}/www-data"
